name: shpazhki
favicon: null
layout_spectrum: 0.18639049981720746
typography_spectrum: 0.9019782524555922
title: shapzhki
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#590104'
    - '#f90d1b'
    - '#299e3e'
    - '#f9db3a'
    - '#8b6b6c'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
